# 1. NORMALIZATION PROBLEM

#### This problem involves normalizing a random 5x5 array. The task is to create a random 5x5 array, normalize it by centering (subtracting the mean), scaling (dividing by the standard deviation), and saving the normalized array as a file named X_normalized.npy.

In [7]:
import numpy as np

#create a random 5x5 array
X = np.random.random((5,5))

#declare variables to be normalized
X_mean=np.mean(X)
X_std=np.std(X)

#normalize values from array
X_normalized = (X - X_mean)/(X_std)

#save array into ".npy" file
np.save('X_normalized.npy', X_normalized)

#output the saved file
print("\nOriginal Array:\n", X)
print("\nNormalized Array:\n", X_normalized) 


Original Array:
 [[0.79664984 0.27155265 0.92836433 0.004249   0.06804399]
 [0.33568409 0.89638093 0.50689198 0.19985007 0.25480116]
 [0.28698618 0.71269332 0.63048028 0.53259781 0.63879378]
 [0.69386411 0.63460522 0.21910993 0.22799096 0.63193623]
 [0.40386896 0.47083254 0.18058965 0.65722671 0.08220831]]

Normalized Array:
 [[ 1.32885131 -0.68784401  1.83471577 -1.71445397 -1.46944208]
 [-0.44153993  1.71187986  0.21600337 -0.96322588 -0.75217998]
 [-0.62856979  1.00640677  0.69065826  0.31472953  0.7225872 ]
 [ 0.93409104  0.70650059 -0.8892562  -0.8551476   0.69625002]
 [-0.17966818  0.077513   -1.03719771  0.79338099 -1.41504239]]


# 2. DIVISIBLE BY 3 PROBLEM

#### This problem involves creating a 10x10 array containing the squares of the first 100 positive integers. The task is to identify all elements in this array that are divisible by 3 and save the resulting elements as a file named div_by_3.npy.

In [9]:
import numpy as np

#create an array of the first 100 positive integers
squares = np.arange(1, 101) ** 2

#reshape to a 10x10 array
squares_10x10 = squares.reshape(10, 10)

#find all values that are divisible by 3
div_by_3 = squares_10x10[squares_10x10 % 3 == 0]

#save array into ".npy" file
np.save('div_by_3.npy', div_by_3)

#output the saved file
data = np.load('div_by_3.npy')
data

array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])